post:
  tags:
    - Applications
  summary: Скачивание списка заявок в Excel
  description: |
    Формирует Excel-файл со списком заявок по переданным фильтрам.

    Фильтры соответствуют фильтрам метода получения списка заявок.
    Если фильтры не переданы, API возвращает Excel-файл со всеми заявками,
    доступными текущему пользователю с учетом его роли и прав доступа.
  operationId: downloadApplicationsExcel
  security:
    - BearerAuth: []
  requestBody:
    $ref: '../components/requestBodies/applications.yaml#/DownloadApplicationsExcelRequestBody'
  responses:
    '200':
      $ref: '../components/responses/applications.yaml#/DownloadApplicationsExcel200Response'
    '400':
      $ref: '../components/responses/common.yaml#/BadRequestErrorResponse'
    '401':
      $ref: '../components/responses/common.yaml#/UnauthorizedErrorResponse'
    '403':
      $ref: '../components/responses/common.yaml#/ForbiddenErrorResponse'
    '429':
      $ref: '../components/responses/common.yaml#/TooManyRequestsErrorResponse'
    '500':
      $ref: '../components/responses/common.yaml#/InternalServerErrorResponse'
