@startuml
title Sequence-диаграмма UC-01: Создание заявки на обучение

actor "Заявитель" as Requester
participant "Портал" as Portal
database "БД Портала" as DB
participant "СДО" as LMS
participant "Почтовая служба" as Mail
actor "Согласующий" as Approver

autonumber

== Открытие формы создания заявки ==

Requester -> Portal: Инициировать создание заявки\nGET /api/v1/users/current
activate Portal

Portal -> DB: Запросить сведения о Заявителе\nи его организации
activate DB
DB --> Portal: Сведения о Заявителе\nи его организации
deactivate DB

Portal --> Requester: 200 CurrentUserResponse\nОтобразить форму создания заявки\nсо всеми полями и заполненными сведениями
deactivate Portal

opt Загрузка ранее сохранённого черновика
    Requester -> Portal: Инициировать загрузку черновика\nGET /api/v1/applications?application_state_id={draft}
    activate Portal
    Portal -> DB: Запросить черновики Заявителя
    activate DB
    DB --> Portal: Данные черновиков
    deactivate DB

    Portal --> Requester: 200 ApplicationsListResponse\nОтобразить список черновиков\nв виде списка

    Requester -> Portal: Выбрать черновик из списка\nGET /api/v1/applications/{id}

    Portal -> DB: Запросить данные выбранного черновика
    activate DB
    DB --> Portal: Данные выбранного черновика
    deactivate DB

    Portal --> Requester: 200 ApplicationDetailsResponse\nЗагрузить данные черновика
    deactivate Portal
end

== Выбор курса ==

Requester -> Portal: Ввести часть названия курса\nGET /api/v1/lms/courses?search={course_name}
activate Portal

Portal -> LMS: Запросить список актуальных курсов\nпо введённому значению\nGET /api/v1/lms/courses
activate LMS
deactivate Portal
deactivate LMS
alt Запрос выполнен корректно
    LMS --> Portal: 200 LmsCoursesListResponse\nНайденные актуальные курсы
    activate LMS
    activate Portal
    deactivate LMS
    Portal --> Requester: 200 LmsCoursesListResponse\nОтобразить найденные курсы
    deactivate Portal
else #LightPink Некорректные параметры запроса
    LMS --> Portal: 400 ErrorResponse\nОшибка получения списка курсов
    activate LMS
    activate Portal
    deactivate LMS
    Portal --> Requester: 400 ErrorResponse\nОтобразить сообщение об ошибке
    deactivate Portal
end

Requester -> Portal: Выбрать курс\nиз списка найденных курсов
activate Portal
Portal --> Requester: Заполнить данные курса\nи даты обучения в форме заявки
deactivate Portal

== Формирование списка учеников ==

loop Повторяется необходимое количество раз
    ... Добавление учеников вручную ...

    Requester -> Portal: Инициировать добавление ученика
    activate Portal
    Portal --> Requester: Отобразить строку для ввода ученика
    deactivate Portal

    Requester -> Portal: Ввести часть ФИО ученика\nGET /api/v1/students?search={full_name}
    activate Portal

    Portal -> DB: Выполнить поиск ученика по ФИО
    activate DB
    DB --> Portal: Найденные ученики
    deactivate DB

    alt Запрос выполнен корректно
        Portal --> Requester: 200 StudentsListResponse\nОтобразить список найденных учеников
    else #LightPink Некорректные параметры поиска
        Portal --> Requester: 400 ErrorResponse\nОтобразить сообщение об ошибке поиска
        deactivate Portal
    end

    Requester -> Portal: Выбрать ученика из списка
    activate Portal
    Portal --> Requester: Автоматически заполнить данные ученика
    deactivate Portal

    opt Удаление ученика из списка
        Requester -> Portal: Выбрать ученика
        activate Portal
        Portal --> Requester: Отметить выбранного ученика
        deactivate Portal

        Requester -> Portal: Инициировать удаление ученика\nиз списка учеников
        activate Portal
        Portal --> Requester: Удалить ученика из списка
        deactivate Portal
    end

    opt Скачать шаблон Excel-файла
        Requester -> Portal: Нажать «Скачать шаблон»\nGET /api/v1/applications/downloads
        activate Portal
        alt Шаблон успешно сформирован
            Portal --> Requester: 200 DownloadApplicationStudentsTemplate200Response\nПередать шаблон Excel-файла
        else #LightPink Ошибка запроса
            Portal --> Requester: 400 ErrorResponse\nОтобразить сообщение об ошибке скачивания
            deactivate Portal
        end
    end

    opt Загрузка списка учеников через Excel
        loop Загрузка Excel-файла до успешной проверки данных
            Requester -> Portal: Загрузить Excel-файл\nсо списком учеников\nPOST /api/v1/students
            activate Portal

            Portal -> Portal: Проверить загруженный файл\nи содержащиеся в нём данные
            Portal --> Portal: Результат проверки файла

            alt #LightPink В загруженном файле обнаружены ошибки
                Portal --> Requester: 400 ErrorResponse\nВернуть ошибку с деталями,\nкоторые требуют доработки
                Portal --> Requester: Вернуть к выбору файла\nдля повторной загрузки
            else #White Загруженный файл прошёл проверку
                Portal --> Requester: 200 UploadStudentsExcelResponse\nОтобразить загруженный список учеников
                deactivate Portal
            end
        end
    end
end

== Операции со списком учеников ==

ref over Requester, Portal
    Операции со списком учеников
    см. students-list-operations.plantuml
end ref

== Отправка заявки на рассмотрение ==

Requester -> Portal: Инициировать отправку заявки\nна рассмотрение\nPOST /api/v1/applications
activate Portal
Portal -> Portal: Проверить обязательные поля,\nформат данных и дубли учеников
Portal --> Portal: Результат проверки заявки

alt #LightPink Обнаружены незаполненные обязательные поля
    Portal --> Requester: 400 ErrorResponse\nСформировать сообщение\nс перечнем незаполненных полей
    Portal --> Requester: Визуально выделить\nнезаполненные обязательные поля
else #LightPink Обнаружены дубли в списке учеников
    Portal --> Requester: 400 ErrorResponse\nСформировать сообщение\nо найденных дублях
    Portal --> Requester: Визуально выделить\nдублирующиеся записи
else #White Заявка валидна
    Portal -> DB: Сохранить заявку\nс соответствующим статусом
    activate DB
    DB --> Portal: Заявка сохранена
    deactivate DB

    Portal -> Mail: Передать email-уведомление\nдля Согласующего
    activate Mail
    Mail --> Approver: Email о новой заявке
    deactivate Mail

    Portal --> Requester: 200 CreateApplicationResponse\nСообщение «Заявка успешно отправлена»
    deactivate Portal
end

opt Сохранение заявки как черновика
    Requester -> Portal: Инициировать сохранение заявки\nв качестве черновика\nPOST /api/v1/applications
    activate Portal

    Portal -> Portal: Проверить доступные данные заявки
    Portal --> Portal: Доступные данные заявки проверены

    alt #LightPink Данные черновика не соответствуют допустимой модели
        Portal --> Requester: 400 ErrorResponse\nОтобразить сообщение об ошибке сохранения черновика
    else #White Черновик может быть сохранён
        Portal -> DB: Сохранить заявку\nс соответствующим статусом
        activate DB
        DB --> Portal: Черновик сохранён
        deactivate DB

        Portal --> Requester: 200 CreateApplicationResponse\nСообщение «Черновик сохранён»
        deactivate Portal
    end
end

@enduml
