@startuml
title Sequence-диаграмма UC-01: Создание заявки на обучение

actor "Заявитель" as Requester
participant "Портал" as Portal
database "БД Портала" as DB
participant "СДО" as LMS
participant "Почтовая служба" as Mail
actor "Согласующий" as Approver

autonumber

== Открытие формы создания заявки ==

Requester -> Portal: Инициировать создание заявки
activate Portal

Portal -> DB: Запросить сведения о Заявителе\nи его организации
activate DB
DB --> Portal: Сведения о Заявителе\nи его организации
deactivate DB

Portal --> Requester: Отобразить форму создания заявки\nсо всеми полями и заполненными сведениями
deactivate Portal

opt Загрузка ранее сохранённого черновика
    Requester -> Portal: Инициировать загрузку черновика
    activate Portal
    Portal -> DB: Запросить черновики Заявителя
    activate DB
    DB --> Portal: Данные черновиков
    deactivate DB
    Portal --> Requester: Отобразить список черновиков\nв виде списка
    Requester -> Portal: Выбрать черновик из списка
    Portal --> Requester: Загрузить данные черновика
    deactivate Portal
end

== Выбор курса ==

Requester -> Portal: Ввести часть названия курса
activate Portal

Portal -> LMS: Запросить список актуальных курсов\nпо введённому значению
activate LMS
LMS --> Portal: Найденные актуальные курсы
deactivate LMS

Portal --> Requester: Отобразить найденные курсы
deactivate Portal

Requester -> Portal: Выбрать курс\nиз списка найденных курсов
activate Portal
Portal --> Requester: Заполнить данные курса\nи даты обучения в форме заявки
deactivate Portal

== Формирование списка учеников ==

loop Повторяется необходимое количество раз
    ... Добавление учеников вручную ...

    Requester -> Portal: Иницировать добавление ученика
    activate Portal
    Portal --> Requester: Отобразить строку для ввода ученика
    deactivate Portal

    Requester -> Portal: Ввести часть ФИО ученика
    activate Portal

    Portal -> DB: Выполнить поиск ученика по ФИО
    activate DB
    DB --> Portal: Найденные ученики
    deactivate DB

    Portal --> Requester: Отобразить список найденных учеников
    deactivate Portal

    Requester -> Portal: Выбрать ученика из списка
    activate Portal
    Portal --> Requester: Автоматически заполнить данные ученика
    deactivate Portal

    opt Удаление ученика из списка
        Requester -> Portal: Выбрать ученика
        activate Portal
        Portal --> Requester: Отметить выбранного ученика
        deactivate Portal

        Requester -> Portal: Инициировать удаление ученика\nиз списка учеников
        activate Portal
        Portal --> Requester: Удалить ученика из списка
        deactivate Portal
    end

    opt Скачать шаблон Excel-файла
        Requester -> Portal: Нажать «Скачать шаблон»
        activate Portal
        Portal --> Requester: Передать шаблон Excel-файла
        deactivate Portal
    end

    opt Загрузка списка учеников через Excel
        loop Загрузка Excel-файла до успешной проверки данных
            Requester -> Portal: Загрузить Excel-файл\nсо списком учеников
            activate Portal

            Portal -> Portal: Проверить загруженный файл\nи содержащиеся в нём данные
            Portal --> Portal: Результат проверки файла

            alt В загруженном файле обнаружены ошибки
                Portal --> Requester: Вернуть ошибку с деталями,\nкоторые требуют доработки
                Portal --> Requester: Вернуть к выбору файла\nдля повторной загрузки
            else Загруженный файл прошёл проверку
                Portal --> Requester: Отобразить загруженный список учеников
                deactivate Portal
            end
        end
    end
end

== Операции со списком учеников ==

opt Поиск по списку учеников
    Requester -> Portal: Ввести поисковый запрос\nпо списку учеников
    activate Portal
    Portal -> Portal: Выполнить поиск\nпо списку учеников
    Portal --> Portal: Результат поиска\nпо списку учеников
    alt Ученики по поисковому запросу не найдены
        Portal --> Requester: Отобразить пустой список учеников
        Requester -> Portal: Изменить поисковый запрос\nили сбросить поиск
        Portal -> Portal: Выполнить повторный поиск\nпо списку учеников
        Portal --> Portal: Результат повторного поиска
        Portal --> Requester: Отобразить актуальный список учеников
    else Ученики по поисковому запросу найдены
        Portal --> Requester: Отобразить найденных учеников
        deactivate Portal
    end
end

opt Фильтрация списка учеников
    Requester -> Portal: Выбрать параметры фильтрации\nсписка учеников
    activate Portal
    Portal -> Portal: Применить выбранные фильтры\nк списку учеников
    Portal --> Portal: Результат применения фильтров
    alt Ученики по выбранным фильтрам не найдены
        Portal --> Requester: Отобразить пустой список учеников
        Requester -> Portal: Изменить параметры фильтрации\nили сбросить фильтры
        Portal -> Portal: Применить обновлённые фильтры\nк списку учеников
        Portal --> Portal: Результат применения обновлённых фильтров
    else Ученики по выбранным фильтрам найдены
        Portal --> Requester: Отобразить отфильтрованный список учеников
        deactivate Portal
    end
end

opt Сортировка списка учеников
    Requester -> Portal: Выбрать параметр сортировки\nсписка учеников
    activate Portal
    Portal -> Portal: Отсортировать список учеников\nпо выбранному параметру
    Portal --> Portal: Список учеников отсортирован
    Portal --> Requester: Отобразить отсортированный список учеников
    deactivate Portal
end

opt Пагинация списка учеников
    Requester -> Portal: Выбрать страницу списка учеников\nили количество учеников на странице
    activate Portal
    Portal -> Portal: Применить параметры пагинации
    Portal --> Portal: Параметры пагинации применены
    Portal --> Requester: Отобразить выбранную страницу\nсписка учеников
    deactivate Portal
end

== Отправка заявки на рассмотрение ==

Requester -> Portal: Инициировать отправку заявки\nна рассмотрение
activate Portal
Portal -> Portal: Проверить обязательные поля,\nформат данных и дубли учеников
Portal --> Portal: Результат проверки заявки

alt Обнаружены незаполненные обязательные поля
    Portal --> Requester: Сформировать сообщение\nс перечнем незаполненных полей
    Portal --> Requester: Визуально выделить\nнезаполненные обязательные поля
else Обнаружены дубли в списке учеников
    Portal --> Requester: Сформировать сообщение\nо найденных дублях
    Portal --> Requester: Визуально выделить\nдублирующиеся записи
else Заявка валидна
    Portal -> DB: Сохранить заявку\nс соответствующим статусом
    activate DB
    DB --> Portal: Заявка сохранена
    deactivate DB


    Portal -> Mail: Передать email-уведомление\nдля Согласующего
    activate Mail
    Mail --> Approver: Email о новой заявке
    deactivate Mail

    Portal --> Requester: Сообщение «Заявка успешно отправлена»
    deactivate Portal
end

opt Сохранение заявки как черновика
    Requester -> Portal: Инициировать сохранение заявки\nв качестве черновика
    activate Portal

    Portal -> Portal: Проверить доступные данные заявки
    Portal --> Portal: Доступные данные заявки проверены

    Portal -> DB: Сохранить заявку\nс соответствующим статусом
    activate DB
    DB --> Portal: Черновик сохранён
    deactivate DB

    Portal --> Requester: Сообщение «Черновик сохранён»
    deactivate Portal
end

@enduml
