@startuml
title Sequence-диаграмма UC-03: Рассмотрение заявки

actor "Согласующий" as Approver
actor "Заявитель" as Requester
participant "Портал" as Portal
database "БД Портала" as DB
participant "СДО" as LMS
participant "Почтовая служба" as Mail

autonumber

== Открытие заявки для рассмотрения ==

Approver -> Portal: Выбрать заявку для рассмотрения\nGET /api/v1/applications/{id}
activate Portal

Portal -> DB: Запросить данные выбранной заявки,\nроль пользователя и права доступа
activate DB
DB --> Portal: Данные заявки,\nроль пользователя и права доступа
deactivate DB

alt Заявка найдена и доступна для просмотра
    Portal -> Portal: Проверить, что Согласующий\nне является создателем заявки
    Portal --> Portal: Результат проверки автора заявки

    Portal -> Portal: Проверить статус заявки\nна доступность для рассмотрения
    Portal --> Portal: Результат проверки статуса заявки

    alt #LightPink Согласующий является создателем заявки
        Portal --> Approver: 200 ApplicationDetailsResponse\nОткрыть карточку заявки
        Portal --> Approver: Не отображать действия\nдля рассмотрения заявки
    else #LightPink Заявка находится в статусе,\nнедоступном для рассмотрения
        Portal --> Approver: 200 ApplicationDetailsResponse\nОткрыть карточку заявки\nтолько для просмотра
        Portal --> Approver: Не отображать действия\nдля рассмотрения заявки
    else #White Заявка доступна для рассмотрения
        Portal --> Approver: 200 ApplicationDetailsResponse\nОткрыть карточку заявки
        Portal --> Approver: Отобразить действия\nдля рассмотрения заявки
    end
else #LightPink Некорректный запрос или заявка недоступна
    Portal --> Approver: 400 ErrorResponse\nОтобразить сообщение об ошибке\nоткрытия карточки заявки
    deactivate Portal
end

opt Скачать заявку
    Approver -> Portal: Инициировать скачивание заявки\nPOST /api/v1/applications/downloads\nDownloadApplicationsRequest
    activate Portal

    Portal -> Portal: Проверить доступ\nк выбранной заявке
    Portal --> Portal: Результат проверки доступа

    alt Заявка доступна для скачивания
        Portal -> DB: Запросить данные заявки\nдля формирования файла
        activate DB
        DB --> Portal: Данные заявки
        deactivate DB

        Portal -> Portal: Сформировать файл заявки

        alt Файл сформирован
            Portal --> Approver: 200 DownloadApplications200Response\nПередать файл заявки
        else #LightPink Ошибка формирования файла
            Portal --> Approver: 400 ErrorResponse\nСообщение об ошибке скачивания
        end

    else #LightPink Заявка недоступна для скачивания
        Portal --> Approver: 400 ErrorResponse\nСообщение об отсутствии доступа\nк скачиванию заявки
        deactivate Portal
    end
end

== Операции со списком учеников ==

ref over Approver, Portal
    Операции со списком учеников
    см. REF_StudentsListOperations
end ref

== Принятие решения по заявке ==

alt Согласующий согласует заявку
    Approver -> Portal++: Инициировать согласование заявки\nPOST /api/v1/applications/{id}/state\nChangeApplicationStateRequest\napplication_state_id = «Согласована»
    deactivate Portal
    ref over Approver, Requester, Portal, DB, Mail
        Контрольная проверка заявки, сохранение статуса и уведомление участников
        см. REF_UpdateStatusAndNotify
    end ref

    == Передача согласованной заявки в СДО ==
    Portal -> LMS: Передать согласованную заявку\nPOST /api/v1/lms/applications\nCreateLmsApplicationRequest
    activate Portal
    activate LMS

    alt СДО приняло заявку на обработку
        LMS --> Portal: CreateLmsApplicationAcceptedResponse
        deactivate LMS

        Portal -> DB: Зафиксировать успешную\nпередачу заявки в СДО
        activate DB
        DB --> Portal: Передача заявки в СДО зафиксирована
        deactivate DB

        Portal --> Approver: Отобразить заявку\nс соответствующим статусом\nи признаком передачи в СДО
    else #LightPink Нет доступа к СДО или ошибка СДО
        LMS --> Portal: ErrorResponse
        deactivate LMS
        deactivate Portal

        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref

        Portal --> Approver: Отобразить заявку\nс соответствующим статусом
        activate Portal
        deactivate Portal
        break Процесс рассмотрения заявки прерван\nиз-за ошибки передачи в СДО
        end
    end

    ... В течение 5 рабочих дней\nс момента создания заявки\nСДО проверяет заявку ...

    == Получение решения от СДО ==

    alt СДО приняло заявку
        LMS -> Portal: Передать решение по заявке\nPOST /api/v1/lms/webhooks/applications/{id}/state\nLmsApplicationStateWebhookRequest\nevent_type = accepted
        activate LMS
        activate Portal
        deactivate LMS
        deactivate Portal
        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref
        Portal --> LMS++: LmsApplicationStateWebhookAcceptedResponse
        activate Portal
        deactivate LMS
        Portal --> Approver: Отобразить заявку\nс соответствующим статусом
        deactivate Portal

        ... Проходит обучение по заявке ...
        
        LMS -> Portal: Передать событие о завершении обучения\nPOST /api/v1/lms/webhooks/applications/{id}/state\nLmsApplicationStateWebhookRequest\nevent_type = completed
        activate Portal
        activate LMS
        deactivate LMS
        deactivate Portal
        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref

        Portal --> LMS: LmsApplicationStateWebhookAcceptedResponse
        activate LMS
        activate Portal
        deactivate LMS
        Portal --> Approver: Отобразить заявку\nс соответствующим статусом
        deactivate Portal
        == Архивирование заявки ==

        ... Через 3 года после завершения заявки ...

        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref

    else СДО отложило заявку
        LMS -> Portal: Передать решение по заявке\nPOST /api/v1/lms/webhooks/applications/{id}/state\nLmsApplicationStateWebhookRequest\nevent_type = postponed
        activate Portal
        activate LMS
        deactivate LMS
        deactivate Portal
        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref

        Portal --> LMS: LmsApplicationStateWebhookAcceptedResponse
        activate LMS
        activate Portal
        deactivate LMS
        Portal --> Approver: Отобразить заявку\nс соответствующим статусом
        deactivate Portal
    else #LightPink СДО передало некорректное событие
        LMS -> Portal: Передать некорректное событие по заявке\nPOST /api/v1/lms/webhooks/applications/{id}/state\nLmsApplicationStateWebhookRequest
        activate Portal
        activate LMS
        Portal --> LMS: ErrorResponse\nСобытие СДО не принято
        deactivate Portal
        deactivate LMS
    end
else Согласующий отклоняет заявку

    Approver -> Portal: Инициировать отклонение заявки
    activate Portal
    Portal --> Approver: Запросить комментарий\nс причиной отклонения
    Approver -> Portal: Ввести комментарий\nPOST /api/v1/applications/{id}/state\nChangeApplicationStateRequest\napplication_state_id = «Отклонена»
    Portal -> Portal: Проверить наличие комментария
    Portal --> Portal: Результат проверки комментария

    alt #LightPink Комментарий не указан
        Portal --> Approver: 400 ErrorResponse\nСообщение «Необходимо указать\nпричину отклонения»
        deactivate Portal
    else #White Комментарий указан
        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref

        Portal --> Approver: Отобразить заявку\nс соответствующим статусом
        activate Portal
        deactivate Portal

        == Архивирование отклонённой заявки ==

        ... Через 3 года после отклонения заявки ...

        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref
    end
else Согласующий отправляет заявку на корректировку
    Approver -> Portal: Инициировать отправку заявки\nна корректировку
    activate Portal
    Portal --> Approver: Запросить комментарий\nс деталями корректировки
    Approver -> Portal: Ввести комментарий\nPOST /api/v1/applications/{id}/state\nChangeApplicationStateRequest\napplication_state_id = «На корректировке»
    Portal -> Portal: Проверить наличие комментария
    Portal --> Portal: Результат проверки комментария

    alt #LightPink Комментарий не указан
        Portal --> Approver: 400 ErrorResponse\nСообщение «Необходимо указать\nдетали корректировки»
        deactivate Portal
    else #White Комментарий указан
        ref over Approver, Requester, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref
        
        Portal --> Approver: Отобразить заявку\nс соответствующим статусом
        activate Portal
        deactivate Portal
    end
end

@enduml
