@startuml
title Sequence-диаграмма UC-03: Рассмотрение заявки

actor "Согласующий" as Approver
actor "Заявитель" as Requester
boundary "Frontend" as Frontend
participant "Портал" as Portal
database "БД Портала" as DB
participant "СДО" as LMS
participant "Почтовая служба" as Mail

autonumber

== Открытие заявки для рассмотрения ==

Approver -> Frontend: Выбрать заявку для рассмотрения
activate Frontend

Frontend -> Portal: GET /api/v1/applications/{id}
activate Portal

Portal -> DB: Запросить данные выбранной заявки,\nроль пользователя и права доступа
activate DB
DB --> Portal: Данные заявки,\nроль пользователя и права доступа
deactivate DB

alt Заявка найдена и доступна для просмотра

    Portal -> Portal: Проверить, что Согласующий\nне является создателем заявки
    Portal --> Portal: Результат проверки автора заявки

    Portal -> Portal: Проверить статус заявки\nна доступность для рассмотрения
    Portal --> Portal: Результат проверки статуса заявки

    break #LightPink Согласующий является создателем заявки
        Portal --> Frontend: 200 OK\nОткрыть карточку заявки
        Frontend --> Approver: Открыть карточку заявки
        Frontend --> Approver: Не отображать действия\nдля рассмотрения заявки
    end break

    break #LightPink Заявка находится в статусе,\nнедоступном для рассмотрения
        Portal --> Frontend: 200 OK\nОткрыть карточку заявки (только просмотр)
        Frontend --> Approver: Открыть карточку заявки\nтолько для просмотра
        Frontend --> Approver: Не отображать действия\nдля рассмотрения заявки
    end break

    Portal --> Frontend: 200 OK\nОткрыть карточку заявки
    Frontend --> Approver: Открыть карточку заявки
    Frontend --> Approver: Отобразить действия\nдля рассмотрения заявки

else #LightPink Некорректный запрос или заявка недоступна
    Portal --> Frontend: 404 Not Found
    deactivate Portal

    Frontend --> Approver: Отобразить ошибку 404
    deactivate Frontend
end

opt Скачать заявку
    Approver -> Frontend: Инициировать скачивание заявки
    activate Frontend

    Frontend -> Portal: POST /api/v1/applications/downloads
    activate Portal

    Portal -> Portal: Проверить доступ\nк выбранной заявке
    Portal --> Portal: Результат проверки доступа

    alt Заявка доступна для скачивания
        Portal -> DB: Запросить данные заявки\nдля формирования файла
        activate DB
        DB --> Portal: Данные заявки
        deactivate DB

        Portal -> Portal: Сформировать файл заявки

        alt Файл сформирован
            Portal --> Frontend: 200 OK\nПередать файл заявки
            Frontend --> Approver: Скачать файл заявки
        else #LightPink Ошибка формирования файла
            Portal --> Frontend: 500 Internal Server Error\nСообщение об ошибке скачивания
            Frontend --> Approver: Отобразить ошибку скачивания
        end

    else #LightPink Заявка недоступна для скачивания
        Portal --> Frontend: 403 Forbidden\nСообщение об отсутствии доступа\nк скачиванию заявки
        deactivate Portal
        Frontend --> Approver: Отобразить сообщение об отсутствии доступа
        deactivate Frontend
    end
end

== Операции со списком учеников ==

ref over Approver, Portal
    Операции со списком учеников
    см. REF_StudentsListOperations
end ref

== Принятие решения по заявке ==

alt Согласующий согласует заявку
    Approver -> Frontend: Инициировать согласование заявки\napplication_state_id = «Согласована»
    activate Frontend

    Frontend -> Portal: PATCH /api/v1/applications/{id}/state
    deactivate Frontend

    ref over Approver, Requester, Frontend, Portal, DB, Mail
        Контрольная проверка заявки, сохранение статуса и уведомление участников
        см. REF_UpdateStatusAndNotify
    end ref

    Portal --> Frontend: 200 OK
    activate Frontend
    Frontend --> Approver: Отобразить заявку\nс соответствующим статусом
    deactivate Frontend
    ... Передача согласованной заявки в СДО ...
    alt СДО приняло заявку на обработку
        Portal -> LMS: Передать согласованную заявку\nPOST /api/v1/lms/applications
        activate Portal
        activate LMS
        LMS --> Portal: 202 Accepted
        deactivate Portal
        deactivate LMS
    else #LightPink Нет доступа к СДО или ошибка СДО
        break
            loop 5 попыток
                Portal -> LMS: Передать согласованную заявку\nPOST /api/v1/lms/applications
                activate Portal
                activate LMS
                LMS --> Portal: 500 Internal Server Error / 4xx: Client Error   
                deactivate Portal
                deactivate LMS
            end

            ref over Approver, Requester, Frontend, Portal, DB, Mail
                Контрольная проверка заявки, сохранение статуса и уведомление участников
                см. REF_UpdateStatusAndNotify
            end ref
        end
    end

    ref over Approver, Requester, Frontend, Portal, DB, Mail
        Контрольная проверка заявки, сохранение статуса и уведомление участников
        см. REF_UpdateStatusAndNotify
    end ref

    ... Получение решения от СДО, в течении 5 рабочих дней\nс момента создания заявки\nСДО проверяет заявку ...
    alt СДО приняло заявку
        LMS -> Portal: Передать решение по заявке\nPOST /api/v1/lms/webhooks/applications/{id}/state\nevent_type = accepted
        activate LMS
        activate Portal
        Portal --> LMS: 200 OK
        deactivate LMS
        deactivate Portal
        ref over Approver, Requester, Frontend, Portal, DB, Mail
            Контрольная проверка заявки, сохранение статуса и уведомление участников
            см. REF_UpdateStatusAndNotify
        end ref

        ... Проходит обучение по заявке ...
        
        LMS -> Portal: Передать событие о завершении обучения\nPOST /api/v1/lms/webhooks/applications/{id}/state\nevent_type = completed
        activate Portal
        activate LMS
        Portal --> LMS: 200 OK
        deactivate LMS
        deactivate Portal
    else СДО отложило заявку
        LMS -> Portal: Передать решение по заявке\nPOST /api/v1/lms/webhooks/applications/{id}/state\nevent_type = postponed
        activate Portal
        activate LMS
        Portal --> LMS: 200 OK
        deactivate LMS
        deactivate Portal
    else #LightYellow Обработка ошибок ответа от СДО
        loop #LightPink 5 попыток
            LMS -> Portal: Передать некорректное событие по заявке\nPOST /api/v1/lms/webhooks/applications/{id}/state
            activate Portal
            activate LMS
            Portal --> LMS: 500 Internal Server Error / 4xx: Client Error\nСобытие СДО не принято
            deactivate Portal
            deactivate LMS
        end

        ...Прошло 2 недели...
        Portal -> LMS: GET /api/v1/lms/applications/status\napplication_ids: [APP-000001, APP-000002, APP-000003]
        activate Portal
        activate LMS
        LMS  --> Portal: 200 OK
        deactivate Portal
        deactivate LMS
    end
    ... Вне зависимости от решения СДО, заявка будет сохранена в соответствующем статусе...
    ref over Approver, Requester, Frontend, Portal, DB, Mail
        Контрольная проверка заявки, сохранение статуса и уведомление участников
        см. REF_UpdateStatusAndNotify
    end ref
else Согласующий отклоняет заявку
    Approver -> Frontend: Инициировать отклонение заявки
    activate Frontend
    Frontend -> Approver: Инициировать отклонение заявки
    Frontend --> Approver: Отобразить поле ввода комментария\nи заблокировать кнопку отправки
    Approver -> Frontend: Ввести комментарий\nс причиной отклонения
    Frontend -> Frontend: Проверить заполнение комментария
    Frontend --> Frontend: Комментарий заполнен
    Frontend --> Approver: Разблокировать кнопку отправки
    Approver -> Frontend: Подтвердить отклонение заявки
    Frontend -> Portal: PATCH /api/v1/applications/{id}/state
    deactivate Frontend

    ref over Approver, Requester, Frontend, Portal, DB, Mail
        Контрольная проверка заявки, сохранение статуса и уведомление участников
        см. REF_UpdateStatusAndNotify
    end ref

    Portal --> Frontend: 200 OK
    Frontend --> Approver: Отобразить заявку\nс соответствующим статусом
else Согласующий отправляет заявку на корректировку
    Approver -> Frontend: Инициировать отправку заявки\nна корректировку
    activate Frontend

    Frontend --> Approver: Отобразить поле ввода комментария\nи заблокировать кнопку отправки
    Approver -> Frontend: Ввести комментарий
    Frontend -> Frontend: Проверить заполнение комментария
    Frontend --> Frontend: Комментарий заполнен
    Frontend --> Approver: Разблокировать кнопку отправки

    Approver -> Frontend: Подтвердить отправку заявки\nна корректировку
    Frontend -> Portal: PATCH /api/v1/applications/{id}/state
    deactivate Frontend

    ref over Approver, Requester, Frontend, Portal, DB, Mail
        Контрольная проверка заявки, сохранение статуса и уведомление участников
        см. REF_UpdateStatusAndNotify
    end ref

    Portal --> Frontend: 200 OK
    Frontend --> Approver: Отобразить заявку\nс соответствующим статусом
end

== Архивирование заявки ==

... Через 3 года после последнего изменения заявки ...

ref over Approver, Requester, Frontend, Portal, DB, Mail
    Контрольная проверка заявки, сохранение статуса и уведомление участников
    см. REF_UpdateStatusAndNotify
end ref

@enduml
