openapi: 3.0.3

info:
  title: Training Requests API
  version: 1.0.0
  description: CRUD API для модуля «Заявки на обучение»

servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: Auth
    description: Авторизация и данные текущего пользователя
  - name: Applications
    description: Работа с заявками на обучение
  - name: Students
    description: Поиск, фильтрация и загрузка учеников для заявок на обучение
  - name: Notifications
    description: Получение и фильтрация уведомлений пользователя
  - name: LMS Webhooks
    description: Webhook API Портала для получения событий из Системы дистанционного обучения
  - name: LMS
    description: Получение актуальных курсов из Системы дистанционного обучения

security:
  - BearerAuth: []

paths:
  /api/v1/users/current:
    $ref: './paths/users-current.yaml'
  /api/v1/applications:
    $ref: './paths/applications.yaml'
  /api/v1/applications/{id}:
    $ref: './paths/applications-id.yaml'
  /api/v1/applications/downloads:
    $ref: './paths/applications-downloads.yaml'
  /api/v1/applications/downloads/excel:
    $ref: './paths/applications-downloads-excel.yaml'
  /api/v1/students:
    $ref: './paths/students.yaml'
  /api/v1/lms/webhooks/applications/{id}/state:
    $ref: './paths/lms-webhooks-applications-state.yaml'
  /api/v1/notifications:
    $ref: './paths/notifications.yaml'
  /api/v1/lms/courses:
    $ref: './paths/lms-courses.yaml'
  /api/v1/lms/applications:
    $ref: './paths/lms-applications.yaml'
  /api/v1/lms/applications/status:
    $ref: './paths/lms-applications-status.yaml'
components:
  securitySchemes:
    BearerAuth:
      $ref: './components/securitySchemes.yaml'
    LmsWebhookAuth:
      $ref: './components/securitySchemes/lms-webhook.yaml'
    LmsApiAuth:
      $ref: './components/securitySchemes/lms-api.yaml'

  requestBodies:
    CreateApplicationRequestBody:
      $ref: './components/requestBodies/applications.yaml#/CreateApplicationRequestBody'
    UpdateApplicationRequestBody:
      $ref: './components/requestBodies/applications.yaml#/UpdateApplicationRequestBody'
    ChangeApplicationStateRequestBody:
      $ref: './components/requestBodies/applications.yaml#/ChangeApplicationStateRequestBody'
    DownloadApplicationsRequestBody:
      $ref: './components/requestBodies/applications.yaml#/DownloadApplicationsRequestBody'
    DownloadApplicationsExcelRequestBody:
      $ref: './components/requestBodies/applications.yaml#/DownloadApplicationsExcelRequestBody'
    UploadStudentsExcelRequestBody:
      $ref: './components/requestBodies/students.yaml#/UploadStudentsExcelRequestBody'
    LmsApplicationStateWebhookRequestBody:
      $ref: './components/requestBodies/lms-webhooks.yaml#/LmsApplicationStateWebhookRequestBody'
    CreateLmsApplicationRequestBody:
      $ref: './components/requestBodies/lms.yaml#/CreateLmsApplicationRequestBody'

  responses:
    GetCurrentUser200Response:
      $ref: './components/responses/users.yaml#/GetCurrentUser200Response'
    
    GetApplications200Response:
      $ref: './components/responses/applications.yaml#/GetApplications200Response'

    CreateApplication200Response:
      $ref: './components/responses/applications.yaml#/CreateApplication200Response'
    
    GetApplicationById200Response:
      $ref: './components/responses/applications.yaml#/GetApplicationById200Response'

    UpdateApplication200Response:
      $ref: './components/responses/applications.yaml#/UpdateApplication200Response'

    DeleteApplicationDraft200Response:
      $ref: './components/responses/applications.yaml#/DeleteApplicationDraft200Response'

    ChangeApplicationState200Response:
      $ref: './components/responses/applications.yaml#/ChangeApplicationState200Response'

    DownloadApplicationStudentsTemplate200Response:
      $ref: './components/responses/applications.yaml#/DownloadApplicationStudentsTemplate200Response'

    DownloadApplications200Response:
      $ref: './components/responses/applications.yaml#/DownloadApplications200Response'

    DownloadApplicationsExcel200Response:
      $ref: './components/responses/applications.yaml#/DownloadApplicationsExcel200Response'

    GetStudents200Response:
      $ref: './components/responses/students.yaml#/GetStudents200Response'

    UploadStudentsExcel200Response:
      $ref: './components/responses/students.yaml#/UploadStudentsExcel200Response'

    GetNotifications200Response:
      $ref: './components/responses/notifications.yaml#/GetNotifications200Response'

    GetLmsCourses200Response:
      $ref: './components/responses/lms.yaml#/GetLmsCourses200Response'

    CreateLmsApplication202Response:
      $ref: './components/responses/lms.yaml#/CreateLmsApplication202Response'

    LmsApplicationStateWebhook202Response:
      $ref: './components/responses/lms-webhooks.yaml#/LmsApplicationStateWebhook202Response'

    BadRequestErrorResponse:
      $ref: './components/responses/common.yaml#/BadRequestErrorResponse'
    UnauthorizedErrorResponse:
      $ref: './components/responses/common.yaml#/UnauthorizedErrorResponse'
    ForbiddenErrorResponse:
      $ref: './components/responses/common.yaml#/ForbiddenErrorResponse'
    NotFoundErrorResponse:
      $ref: './components/responses/common.yaml#/NotFoundErrorResponse'
    TooManyRequestsErrorResponse:
      $ref: './components/responses/common.yaml#/TooManyRequestsErrorResponse'
    InternalServerErrorResponse:
      $ref: './components/responses/common.yaml#/InternalServerErrorResponse'

  schemas:
    ApplicationsListResponse:
      $ref: './components/schemas/applications.yaml#/ApplicationsListResponse'

    CreateApplicationRequest:
      $ref: './components/schemas/applications.yaml#/CreateApplicationRequest'

    CreateApplicationResponse:
      $ref: './components/schemas/applications.yaml#/CreateApplicationResponse'

    ApplicationListItem:
      $ref: './components/schemas/applications.yaml#/ApplicationListItem'

    ApplicationStudent:
      $ref: './components/schemas/applications.yaml#/ApplicationStudent'

    ApplicationCourse:
      $ref: './components/schemas/applications.yaml#/ApplicationCourse'

    ApplicationState:
      $ref: './components/schemas/applications.yaml#/ApplicationState'

    ApplicationOrganization:
      $ref: './components/schemas/applications.yaml#/ApplicationOrganization'

    ApplicationUserShort:
      $ref: './components/schemas/applications.yaml#/ApplicationUserShort'

    ApplicationsPaginationMeta:
      $ref: './components/schemas/applications.yaml#/ApplicationsPaginationMeta'

    ApplicationDetailsResponse:
      $ref: './components/schemas/applications.yaml#/ApplicationDetailsResponse'

    UpdateApplicationRequest:
      $ref: './components/schemas/applications.yaml#/UpdateApplicationRequest'

    DeleteApplicationDraftResponse:
      $ref: './components/schemas/applications.yaml#/DeleteApplicationDraftResponse'

    ApplicationPerson:
      $ref: './components/schemas/applications.yaml#/ApplicationPerson'

    ApplicationComment:
      $ref: './components/schemas/applications.yaml#/ApplicationComment'

    ChangeApplicationStateRequest:
      $ref: './components/schemas/applications.yaml#/ChangeApplicationStateRequest'

    DownloadApplicationsRequest:
      $ref: './components/schemas/applications.yaml#/DownloadApplicationsRequest'

    DownloadApplicationsExcelRequest:
      $ref: './components/schemas/applications.yaml#/DownloadApplicationsExcelRequest'

    StudentsListResponse:
      $ref: './components/schemas/students.yaml#/StudentsListResponse'

    Student:
      $ref: './components/schemas/students.yaml#/Student'

    StudentPosition:
      $ref: './components/schemas/students.yaml#/StudentPosition'

    StudentDepartment:
      $ref: './components/schemas/students.yaml#/StudentDepartment'

    StudentOrganization:
      $ref: './components/schemas/students.yaml#/StudentOrganization'

    StudentsPaginationMeta:
      $ref: './components/schemas/students.yaml#/StudentsPaginationMeta'

    UploadStudentsExcelRequest:
      $ref: './components/schemas/students.yaml#/UploadStudentsExcelRequest'

    UploadStudentsExcelResponse:
      $ref: './components/schemas/students.yaml#/UploadStudentsExcelResponse'

    NotificationsListResponse:
      $ref: './components/schemas/notifications.yaml#/NotificationsListResponse'

    Notification:
      $ref: './components/schemas/notifications.yaml#/Notification'

    NotificationsPaginationMeta:
      $ref: './components/schemas/notifications.yaml#/NotificationsPaginationMeta'

    LmsCoursesListResponse:
      $ref: './components/schemas/lms.yaml#/LmsCoursesListResponse'

    LmsCourse:
      $ref: './components/schemas/lms.yaml#/LmsCourse'

    LmsCoursesPaginationMeta:
      $ref: './components/schemas/lms.yaml#/LmsCoursesPaginationMeta'

    CreateLmsApplicationRequest:
      $ref: './components/schemas/lms.yaml#/CreateLmsApplicationRequest'

    CreateLmsApplicationAcceptedResponse:
      $ref: './components/schemas/lms.yaml#/CreateLmsApplicationAcceptedResponse'

    LmsApplicationCourse:
      $ref: './components/schemas/lms.yaml#/LmsApplicationCourse'

    LmsApplicationPerson:
      $ref: './components/schemas/lms.yaml#/LmsApplicationPerson'

    LmsApplicationStudent:
      $ref: './components/schemas/lms.yaml#/LmsApplicationStudent'

    LmsApplicationPosition:
      $ref: './components/schemas/lms.yaml#/LmsApplicationPosition'

    LmsApplicationDepartment:
      $ref: './components/schemas/lms.yaml#/LmsApplicationDepartment'

    LmsApplicationOrganization:
      $ref: './components/schemas/lms.yaml#/LmsApplicationOrganization'

    LmsApplicationStateWebhookRequest:
      $ref: './components/schemas/lms-webhooks.yaml#/LmsApplicationStateWebhookRequest'

    LmsApplicationStateWebhookAcceptedResponse:
      $ref: './components/schemas/lms-webhooks.yaml#/LmsApplicationStateWebhookAcceptedResponse'

    GetLmsApplicationsStatusRequest:
      $ref: './components/schemas/lms.yaml#/GetLmsApplicationsStatusRequest'

    GetLmsApplicationsStatusResponse:
      $ref: './components/schemas/lms.yaml#/GetLmsApplicationsStatusResponse'

    LmsApplicationStatus:
      $ref: './components/schemas/lms.yaml#/LmsApplicationStatus'

    ErrorResponse:
      $ref: './components/schemas/common.yaml'

    CurrentUserResponse:
      $ref: './components/schemas/users.yaml'

  examples:
    ApplicationCannotBeUpdatedByStateExample:
      $ref: './components/examples/applications.yaml#/ApplicationCannotBeUpdatedByStateExample'

    ApplicationUpdateForbiddenNotCreatorExample:
      $ref: './components/examples/applications.yaml#/ApplicationUpdateForbiddenNotCreatorExample'

    ApplicationNotDraftErrorExample:
      $ref: './components/examples/applications.yaml#/ApplicationNotDraftErrorExample'

    InvalidApplicationStateTransitionExample:
      $ref: './components/examples/applications.yaml#/InvalidApplicationStateTransitionExample'

    ApplicationStateCommentRequiredExample:
      $ref: './components/examples/applications.yaml#/ApplicationStateCommentRequiredExample'

    ApplicationApproverIsCreatorExample:
      $ref: './components/examples/applications.yaml#/ApplicationApproverIsCreatorExample'

    ApplicationStateChangeForbiddenExample:
      $ref: './components/examples/applications.yaml#/ApplicationStateChangeForbiddenExample'

    StudentNotFoundInExcelExample:
      $ref: './components/examples/students.yaml#/StudentNotFoundInExcelExample'

    DuplicateStudentsInExcelExample:
      $ref: './components/examples/students.yaml#/DuplicateStudentsInExcelExample'

    ApplicationInvalidStateForLmsEventExample:
      $ref: './components/examples/lms-webhooks.yaml#/ApplicationInvalidStateForLmsEventExample'

    ApplicationApproverNotAssignedExample:
      $ref: './components/examples/lms-webhooks.yaml#/ApplicationApproverNotAssignedExample'

    DuplicateStudentsInApplicationExample:
      $ref: './components/examples/applications.yaml#/DuplicateStudentsInApplicationExample'

    StudentsNotFoundInApplicationExample:
      $ref: './components/examples/applications.yaml#/StudentsNotFoundInApplicationExample'

    CourseNotFoundInApplicationExample:
      $ref: './components/examples/applications.yaml#/CourseNotFoundInApplicationExample'
