fourStayMicroservices.analyticsService -> fourStayMicroservices.analyticsDatabase "Читает и сохраняет агрегированные аналитические данные" "SQL"
fourStayMicroservices.auditService -> fourStayMicroservices.auditDatabase "Читает и сохраняет записи аудита" "SQL"
fourStayMicroservices.billingService -> fourStayMicroservices.billingDatabase "Читает и сохраняет счета, начисления и тарифы" "SQL"
fourStayMicroservices.bookingService -> fourStayMicroservices.bookingDatabase "Читает и сохраняет данные бронирований" "SQL"
fourStayMicroservices.calendarService -> fourStayMicroservices.calendarDatabase "Читает и сохраняет данные календарей" "SQL"
fourStayMicroservices.contentService -> fourStayMicroservices.contentDatabase "Читает и сохраняет CMS-контент" "SQL"
fourStayMicroservices.conversationService -> fourStayMicroservices.conversationDatabase "Читает и сохраняет сообщения и диалоги" "SQL"
fourStayMicroservices.dashboardService -> fourStayMicroservices.dashboardDatabase "Читает и сохраняет данные представлений дашбордов" "SQL"
fourStayMicroservices.dictionaryService -> fourStayMicroservices.dictionaryDatabase "Читает и сохраняет справочные данные" "SQL"
fourStayMicroservices.documentService -> fourStayMicroservices.documentDatabase "Читает и сохраняет метаданные документов и договоров" "SQL"
fourStayMicroservices.documentService -> fourStayMicroservices.documentDatabase "Читает и сохраняет шаблоны документов" "SQL"
fourStayMicroservices.feeService -> fourStayMicroservices.feeDatabase "Хранит тарифы и правила расчета комиссий" "JDBC"
fourStayMicroservices.identityService -> fourStayMicroservices.identityDatabase "Читает и сохраняет учетные данные пользователей" "SQL"
fourStayMicroservices.importService -> fourStayMicroservices.importDatabase "Читает и сохраняет задания импорта" "SQL"
fourStayMicroservices.inventoryService -> fourStayMicroservices.inventoryDatabase "Читает и сохраняет данные доступности" "SQL"
fourStayMicroservices.notificationService -> fourStayMicroservices.notificationDatabase "Читает и сохраняет уведомления" "SQL"
fourStayMicroservices.organisationService -> fourStayMicroservices.organisationDatabase "Читает и сохраняет данные организаций" "SQL"
fourStayMicroservices.personalDataService -> fourStayMicroservices.personalDataDatabase "Читает и сохраняет персональные данные, согласия и журнал запросов ПДн" "SQL"
fourStayMicroservices.paymentService -> fourStayMicroservices.paymentDatabase "Читает и сохраняет данные платежей" "SQL"
fourStayMicroservices.paymentGateway -> fourStayMicroservices.paymentGatewayDatabase "Читает и сохраняет журналы платежных операций" "SQL"
fourStayMicroservices.promotionService -> fourStayMicroservices.promotionDatabase "Читает и сохраняет данные акций" "SQL"
fourStayMicroservices.propertyService -> fourStayMicroservices.propertyDatabase "Читает и сохраняет данные объектов размещения" "SQL"
fourStayMicroservices.reviewService -> fourStayMicroservices.reviewDatabase "Читает и сохраняет отзывы" "SQL"
fourStayMicroservices.searchService -> fourStayMicroservices.searchDatabase "Читает и обновляет поисковый индекс" "REST / TCP"
fourStayMicroservices.taskService -> fourStayMicroservices.taskDatabase "Читает и сохраняет задачи" "SQL"
fourStayMicroservices.userProfileService -> fourStayMicroservices.userProfileDatabase "Читает и сохраняет профили пользователей" "SQL"
