fourStayMicroservices.analyticsService -> fourStayMicroservices.analyticsDatabase "R/W агрегированные аналитические данные" "SQL"
fourStayMicroservices.auditService -> fourStayMicroservices.auditDatabase "R/W записи аудита" "SQL"
fourStayMicroservices.billingService -> fourStayMicroservices.billingDatabase "R/W счета, начисления и тарифы" "SQL"
fourStayMicroservices.bookingService -> fourStayMicroservices.bookingDatabase "R/W данные бронирований" "SQL"
fourStayMicroservices.bookingOrchestrator -> fourStayMicroservices.bookingOrchestratorDatabase "R/W состояние Saga-процессов бронирования" "SQL"
fourStayMicroservices.calendarService -> fourStayMicroservices.calendarDatabase "R/W данные календарей" "SQL"
fourStayMicroservices.contentService -> fourStayMicroservices.contentDatabase "R/W CMS-контент" "SQL"
fourStayMicroservices.conversationService -> fourStayMicroservices.conversationDatabase "R/W сообщения и диалоги" "SQL"
fourStayMicroservices.dashboardService -> fourStayMicroservices.dashboardDatabase "R/W данные представлений дашбордов" "SQL"
fourStayMicroservices.dictionaryService -> fourStayMicroservices.dictionaryDatabase "R/W справочные данные" "SQL"
fourStayMicroservices.documentService -> fourStayMicroservices.documentDatabase "R/W метаданные, шаблоны и договоры" "SQL"
fourStayMicroservices.feeService -> fourStayMicroservices.feeDatabase "Хранит тарифы и правила расчета комиссий" "SQL"
fourStayMicroservices.identityService -> fourStayMicroservices.identityDatabase "R/W учетные данные пользователей" "SQL"
fourStayMicroservices.importService -> fourStayMicroservices.importDatabase "R/W задания импорта" "SQL"
fourStayMicroservices.inventoryService -> fourStayMicroservices.inventoryDatabase "R/W данные доступности" "SQL"
fourStayMicroservices.notificationService -> fourStayMicroservices.notificationDatabase "R/W уведомления" "SQL"
fourStayMicroservices.organisationService -> fourStayMicroservices.organisationDatabase "R/W данные организаций" "SQL"
fourStayMicroservices.personalDataService -> fourStayMicroservices.personalDataDatabase "R/W персональные данные, согласия и журнал запросов ПДн" "SQL"
fourStayMicroservices.paymentService -> fourStayMicroservices.paymentDatabase "R/W данные платежей" "SQL"
fourStayMicroservices.paymentGateway -> fourStayMicroservices.paymentGatewayDatabase "R/W журналы платежных операций" "SQL"
fourStayMicroservices.paymentHistoryService -> fourStayMicroservices.paymentHistoryDatabase "R/W историю платежей и комиссий" "SQL"
fourStayMicroservices.postPaymentService -> fourStayMicroservices.postPaymentDatabase "R/W журнал постплатёжных событий" "SQL"
fourStayMicroservices.promotionService -> fourStayMicroservices.promotionDatabase "R/W данные акций" "SQL"
fourStayMicroservices.propertyService -> fourStayMicroservices.propertyDatabase "R/W данные объектов размещения" "SQL"
fourStayMicroservices.reconciliationService -> fourStayMicroservices.reconciliationDatabase "R/W реестры и результаты сверки" "SQL"
fourStayMicroservices.reviewService -> fourStayMicroservices.reviewDatabase "R/W отзывы" "SQL"
fourStayMicroservices.searchService -> fourStayMicroservices.searchDatabase "R/W поисковый индекс" "SQL"
fourStayMicroservices.taskService -> fourStayMicroservices.taskDatabase "R/W задачи" "SQL"
fourStayMicroservices.userProfileService -> fourStayMicroservices.userProfileDatabase "R/W профили пользователей" "SQL"
