!include analytics.dsl
!include audit.dsl
!include billing.dsl
!include booking.dsl
!include calendar.dsl
!include conversation.dsl
!include content.dsl
!include dashboard.dsl
!include dictionary.dsl
!include identity.dsl
!include import.dsl
!include inventory.dsl
!include landing.dsl
!include notification.dsl
!include organisation.dsl
!include payment_gateway.dsl
!include payment.dsl
!include property.dsl
!include promotion.dsl
!include review.dsl
!include search.dsl
!include task.dsl
!include user_profile.dsl
