components:
  parameters:

    IdempotencyKeyHeader:
      name: Idempotency-Key
      in: header
      required: true
      description: |
        Уникальный ключ идемпотентности запроса.
        Используется для защиты от повторного создания заявки
        при повторной отправке запроса.
      schema:
        type: string
        example: 9f8c2d7e-3a11-4f6b-9c22-123456789abc
