guest = person "Guest" "Searches for, books, and pays for temporary accommodation."
host = person "Host" "Publishes accommodation listings, manages properties, availability, and booking requests."
manager = person "Manager" "Manages accommodation operations, bookings, and property availability."
organisation_admin = person "Organisation Admin" "Manages organisation settings, users, and accommodation resources."
customer_service = person "Customer Service" "Provides customer support, resolves booking issues, payment disputes, and user inquiries."
agent = person "Agent" "Coordinates bookings, assists customers, and manages operational requests."
admin = person "Admin" "Administers the platform, manages system configuration, users, and operational activities."
