openapi: 3.0.2

info:
  title: Training API
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

paths:
  /users/current:
    $ref: "./src/users/api.yaml#/paths/~1users~1current"

  /applications:
    $ref: "./src/applications/api.yaml#/paths/~1applications"

  /applications/{id}:
    $ref: "./src/applications/api.yaml#/paths/~1applications~1{id}"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
