openapi: 3.0.2

info:
  title: Training API
  version: 1.0.0

servers:
  - url: https://portal.example.com/api/v1

tags:
  - name: Applications
    description: Внутренняя логика портала для работы с заявками на обучение

  - name: LMS Integration
    description: Интеграция с системой дистанционного обучения

  - name: Mail Integration
    description: Интеграция с почтовой службой для отправки уведомлений о событиях заявок

paths:
  /users/current:
    $ref: "./src/users/api.yaml#/paths/~1users~1current"

  /applications/search:
    $ref: "./src/applications/api.yaml#/paths/~1applications~1search"

  /applications:
    $ref: "./src/applications/api.yaml#/paths/~1applications"

  /applications/{id}:
    $ref: "./src/applications/api.yaml#/paths/~1applications~1{id}"

  /applications/downloads:
    $ref: "./src/applications/api.yaml#/paths/~1applications~1downloads"

  /applications/downloads/excel:
    $ref: "./src/applications/api.yaml#/paths/~1applications~1downloads~1excel"

  /applications/webhooks/status:
    $ref: "./src/applications/api.yaml#/paths/~1applications~1webhooks~1status"

  /students/search:
    $ref: "./src/students/api.yaml#/paths/~1students~1search"

  # Integrations

  # =========================
  # LMS Integration
  # =========================
  /lms/courses:
    $ref: "./src/integrations/lms/api.yaml#/paths/~1lms~1courses"

  /lms/applications:
    $ref: "./src/integrations/lms/api.yaml#/paths/~1lms~1applications"

  /lms/applications/status:
    $ref: "./src/integrations/lms/api.yaml#/paths/~1lms~1applications~1status"

  # =========================
  # Mail Integration
  # =========================
  /integrations/mail/notifications:
    $ref: "./src/integrations/mail/api.yaml#/paths/~1mail~1notifications"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    MailServiceAuth:
      type: apiKey
      in: header
      name: X-Service-Token
      description: Служебный токен для взаимодействия с почтовой службой

    LmsWebhookAuth:
      type: apiKey
      in: header
      name: X-Service-Token
      description: Служебный токен для проверки webhook-запросов от СДО

    LmsServiceAuth:
      type: apiKey
      in: header
      name: X-Service-Token
      description: Служебный токен для взаимодействия Портала с СДО
